int self_energy_polar_optical_phonon_scattering(
  int Np,
  int NK,
  int NE,
  int NKloc,
  int NEloc,
  int iEshift,
  int *dims,
  int ndims,
  double complex *Gless,
  double complex *sigless,
  double complex *sbuff1,
  double complex *sbuff2,
  double complex *rbuff1, 
  double complex *rbuff2,
  double complex *sbuffH, 
  double complex *rbuffH,
  double complex *pbuff1,
  double complex *pbuff2,
  MPI_Comm comm2d, 
  MPI_Comm comm2d_per,
  double fac1,
  double fac2
);